import {Link} from 'react-router-dom';import {ArrowRight,Clock,Wifi,Heart,Users,Camera,MapPin,Phone} from 'lucide-react';import {motion} from 'framer-motion';import SectionHeading from '../components/SectionHeading';import MenuCard from '../components/MenuCard';import ReviewCarousel from '../components/ReviewCarousel';import {menuItems,gallery} from '../data/menu';
const hero='https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=2200&q=90';
export default function Home(){return <><section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(25,16,13,.72),rgba(25,16,13,.24)),url(${hero})`}}><motion.div className="hero-copy" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.8}}><div className="eyebrow">COFFEE • FOOD • GOOD VIBES</div><h1>Where every sip feels like <em>a little escape.</em></h1><p>Welcome to Butterfly Cafe — a cozy corner for slow mornings, deep conversations and beautiful moments.</p><div className="hero-actions"><Link className="btn primary" to="/menu">Explore Menu <ArrowRight/></Link><Link className="btn ghost" to="/contact">Visit Us</Link></div></motion.div><div className="scroll-cue">Scroll to discover <span/></div><div className="hero-butterfly">🦋</div></section>
<section className="section"><SectionHeading eyebrow="A TASTE WORTH COMING BACK TO" title="Little favourites, big comfort" text="Our best-loved plates and cups, made fresh for your table."/><div className="menu-grid featured">{menuItems.slice(0,3).map(x=><MenuCard key={x.id} item={x}/>)}</div><div className="center-action"><Link className="text-link" to="/menu">View full menu <ArrowRight size={18}/></Link></div></section>
<section className="section mood-section"><SectionHeading eyebrow="MADE FOR YOUR MOOD" title="Choose your kind of moment"/><div className="mood-grid">{[['Coffee date','A warm cup, a little dessert and nowhere else to be.','https://images.unsplash.com/photo-1521017432531-fbd92d768814?auto=format&fit=crop&w=900&q=85'],['Slow morning','Sunlight, a good book and breakfast worth lingering over.','https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=85'],['Work & chill','Good Wi-Fi, calm corners and coffee on repeat.','https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=85'],['Friends & moments','Share a table, order a little too much and stay awhile.','https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85']].map((x,i)=><motion.div className="mood-card" key={x[0]} whileHover={{scale:1.02}}><img src={x[2]} alt=""/><div><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div></motion.div>)}</div></section>
<section className="split section"><div className="split-image"><img src="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=90" alt="Cafe interior"/></div><div className="split-copy"><SectionHeading eyebrow="OUR STORY" title="A cafe made for beautiful pauses" text="Butterfly Cafe was created for people who love good coffee, delicious food and the feeling of having nowhere else to rush to. Every detail is warm, playful and made to feel like yours." center={false}/><Link className="btn dark" to="/about">Read our story <ArrowRight/></Link></div></section>
<section className="cinematic" style={{backgroundImage:`linear-gradient(rgba(32,21,18,.54),rgba(32,21,18,.54)),url(https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=2200&q=90)`}}><div><span>MORE THAN JUST COFFEE</span><h2>It's where conversations become memories.</h2><div className="big-butterfly">🦋</div><Link className="btn light" to="/about">Discover Butterfly <ArrowRight/></Link></div></section>
<section className="section"><SectionHeading eyebrow="A GLIMPSE INSIDE" title="Little moments at Butterfly"/><div className="gallery-preview">{gallery.slice(0,6).map((x,i)=><Link to="/gallery" className={'gallery-tile tile-'+i} key={x}><img src={x} alt="Cafe moment"/></Link>)}</div></section>
<section className="section features"><SectionHeading eyebrow="WHY BUTTERFLY" title="Come for the coffee. Stay for everything else."/><div className="feature-grid">{[[Clock,'Freshly brewed','Fresh coffee made for every order.'],[Heart,'Cozy ambience','A comfortable place to relax.'],[Wifi,'Free Wi-Fi','Perfect for work and study.'],[Camera,'Instagrammable','Beautiful spaces and food.'],[Users,'Group friendly','Perfect for friends and family.'],['₹','Easy payments','UPI, cards and cash.']].map(([Icon,t,d])=><div className="feature-card" key={t}>{typeof Icon==='string'?<b className="rupee">{Icon}</b>:<Icon/>}<h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="review-section"><SectionHeading eyebrow="FROM OUR TABLE TO YOURS" title="What people say"/><ReviewCarousel/></section>
<section className="instagram section"><SectionHeading eyebrow="FOLLOW THE BUTTERFLIES" title="@butterflycafe"/><div className="insta-grid">{gallery.slice(2,7).map(x=><img key={x} src={x} alt="Butterfly Cafe"/>)}</div><div className="center-action"><a className="btn dark" href="https://instagram.com" target="_blank">Follow us <Camera/></a></div></section>
<section className="visit"><div><span>COME SAY HI 🦋</span><h2>See you at Butterfly Cafe.</h2><p><MapPin/> Hyderabad, Telangana</p><p><Clock/> Mon – Sun · 10:00 AM – 11:00 PM</p><div><Link className="btn light" to="/contact">Get Directions <ArrowRight/></Link><a className="btn outline-light" href="tel:+919876543210"><Phone/> Call Us</a></div></div><div className="map-card"><iframe title="map" src="https://www.google.com/maps?q=Hyderabad%2C%20Telangana&output=embed" loading="lazy"/></div></section></>}